// Define types for categories and games
export type Category = {
  icon: string
  title: string
  id: string
}

export type Game = {
  title: string
  description: string
  href: string
  players: string
  image: string
  category: string
}

// Categories data
export const categories: Category[] = [
  { icon: "🏠", title: "Home", id: "home" },
  { icon: "🎮", title: "Lobby", id: "lobby" },
  { icon: "🕹️", title: "Originals", id: "originals" },
  { icon: "🎰", title: "Slots", id: "slots" },
]

export const games: Game[] = [
  {
    title: "Number Sequence",
    description: "Click numbers in sequence to test your attention and speed",
    href: "/games/number",
    players: "21.5K",
    image: "/image-numberclicking.png",
    category: "originals",
  },
  {
    title: "Repair Kit",
    description: "Solve as many math problems as you can within a minute",
    href: "/games/repair-kit",
    players: "21.5K",
    image: "/image-repair.png",
    category: "table-games",
  },
  {
    title: "Path ",
    description: "Memorize and reproduce patterns to test your visual memory",
    href: "/games/path",
    players: "21.5K",
    image: "/image-path.png",
    category: "slots",
  },
  {
    title: "Thermite",
    description: "Remember the light square positions to replicate them later when they hide.",
    href: "/games/thermite",
    players: "21.5K",
    image: "/image-thermite.png",
    category: "slots",
  },
  {
    title: "Var Simulation",
    description: "Solve as many math problems as you can within a minute",
    href: "/games/var-simulation",
    players: "21.5K",
    image: "/image-varsimulation.png",
    category: "live-casino",
  },
  {
    title: "Bodacious",
    description: "Remember the light square positions to replicate them later when they hide.",
    href: "/games/bodacious",
    players: "21.5K",
    image: "/image-bank.png",
    category: "table-games",
  },
  {
    title: "Number Clicking",
    description: "Race against time to click numbers in order from 1 to 20",
    href: "/games/enter",
    players: "21.5K",
    image: "/image-enter.png",
    category: "originals",
  },
  {
    title: "Safe Cracking",
    description: "Navigate through a maze and reach the end as fast as possible",
    href: "/games/safe-cracking",
    players: "21.5K",
    image: "/image-safe.png",
    category: "table-games",
  },
  {
    title: "FingerPrint",
    description: "Navigate through a maze and reach the end as fast as possible",
    href: "/games/finger-print",
    players: "21.5K",
    image: "/image-finger.png",
    category: "originals",
  },
  {
    title: "Jumbled",
    description: "Navigate through a maze and reach the end as fast as possible",
    href: "/games/jumbled",
    players: "21.5K",
    image: "/image-jumbled.png",
    category: "slots",
  },
  {
    title: "Blink Dot",
    description: "Solve as many math problems as you can within a minute",
    href: "/games/blink-dot",
    players: "21.5K",
    image: "/image-dot.png",
    category: "live-casino",
  },
  {
    title: "Math",
    description: "Solve as many math problems as you can within a minute",
    href: "/games/math-game",
    players: "21.5K",
    image: "/image-bypass.png",
    category: "live-casino",
  },
  {
    title: "Untangle",
    description: "Solve as many math problems as you can within a minute",
    href: "/games/untangle",
    players: "21.5K",
    image: "/image-untangle.png",
    category: "live-casino",
  },
]

export interface PricingTier {
  name: string
  price: {
      INR: number
      EUR: number
  }
  defaultCurrency?: 'INR' | 'EUR'
  description: string
  features: string[]
  duration: string
  durationTime: string
  tebexId: string
  popular?: boolean
  imageUrl?: string
}

export const plans: PricingTier[] = [
  {
    name: "STARTER PLAN",
    price: {
      INR: 39,
      EUR: 0.75
    },
    duration: "per month",
    durationTime: "1",
    tebexId: "6694918",
    features: [
      "Access to all mini-games",
      "Starter discord role",
      "24/7 support",
    ],
    description: "",
    imageUrl: "/1month.png"
  },
  {
    name: "BASIC PLAN",
    price: {
      INR: 110,
      EUR: 1.60
    },
    duration: "per 3 months",
    durationTime: "3",
    tebexId: "6694919",
    features: [
      "Access to all mini-games",
      "Basic discord role",
      "24/7 support",
    ],
    description: "",
    imageUrl: "/3month.png"
  },
  {
    name: "PREMIUM PLAN",
    price: {
      INR: 200,
      EUR: 3.00
    },
    duration: "per 6 months",
    popular: true,
    durationTime: "6",
    tebexId: "6694920",
    features: [
      "Access to all mini-games",
      "Premium discord role",
      "24/7 support",
    ],
    description: "",
    imageUrl: "/6month.png"
  },
  {
    name: "ULTIMATE PLAN",
    price: {
      INR: 350,
      EUR: 5.50
    },
    duration: "per 12 months",
    durationTime: "12",
    tebexId: "6694921",
    features: [
      "Access to all mini-games",
      "Ultimate discord role",
      "Custom game requests",
      "24/7 priority support",
    ],
    description: "",
    imageUrl: "/12month.png"
  },
  {
    name: "EXECUTIVE PLAN",
    price: {
      INR: 500,
      EUR: 25
    },
    duration: "Unlimited Period",
    durationTime: "12",
    tebexId: "6694922",
    features: [
      "Access to all mini-games",
      "Executive discord role",
      "Custom game requests",
      "Priority access to new games",
      "VIP support",
    ],
    description: "",
    imageUrl: "/unlimited.png"
  }
]

export const PHRASES = [
  "SHE READS A NOVEL BEFORE BED",
  "THE CAT SAT ON THE MAT",
  "I CAN SEE THE BLUE SKY",
  "A BOY RAN DOWN THE STREET",
  "MY DOG ATE THE BONE FAST",
  "WE PLAY IN THE PARK NOW",
  "THE SUN SETS IN THE WEST",
  "HE DRIVES A RED CAR",
  "SHE LIKES TO PAINT",
  "THE BIRD SINGS IN THE MORNING",
  "I DRINK COFFEE EVERY DAY",
  "THE FLOWERS BLOOM IN SPRING",
  "HE PLAYS THE GUITAR WELL",
  "SHE COOKS DELICIOUS MEALS",
  "THE RAIN FALLS GENTLY",
  "I READ THE NEWS ONLINE",
  "THE CHILDREN LAUGH LOUDLY",
  "SHE WEARS A BLUE DRESS",
  "HE WORKS IN AN OFFICE",
  "THE MOON SHINES BRIGHTLY",
  "I WRITE IN MY JOURNAL",
  "THE DOG BARKS AT NIGHT",
  "SHE DANCES GRACEFULLY",
  "HE RUNS EVERY MORNING",
  "THE TREE GROWS TALL",
  "I WATCH MOVIES ON WEEKENDS",
  "THE WATER IS COLD",
  "SHE PLANTS A GARDEN",
  "HE FIXES CARS",
  "THE WIND BLOWS STRONGLY",
  "I LISTEN TO MUSIC",
  "THE BOOK IS INTERESTING",
  "SHE BAKES BREAD",
  "HE PAINTS THE WALL",
  "THE STARS TWINKLE",
  "I SWIM IN THE POOL",
  "THE FIRE BURNS BRIGHT",
  "SHE SEWS A DRESS",
  "HE BUILDS A HOUSE",
  "THE ICE MELTS",
  "I RIDE A BIKE",
  "THE CLOUDS ARE WHITE",
  "SHE WRITES A LETTER",
  "HE READS A BOOK",
  "THE GRASS IS GREEN",
  "I EAT BREAKFAST",
  "THE ROAD IS LONG",
  "SHE SINGS A SONG",
  "HE PLAYS CHESS",
  "THE RIVER FLOWS",
  "I DRAW A PICTURE",
  "THE SKY IS CLEAR",
  "SHE DRINKS TEA",
  "HE PLAYS FOOTBALL",
  "THE LEAVES FALL",
  "I GO TO SCHOOL",
  "THE MOUNTAIN IS HIGH",
  "SHE RIDES A HORSE",
  "HE CATCHES FISH",
  "THE SEA IS CALM",
  "I WRITE A STORY",
  "THE SUN RISES",
  "SHE PLAYS THE PIANO",
  "HE TAKES PHOTOS",
  "THE BIRD FLIES",
  "I READ A MAGAZINE",
  "THE WIND IS STRONG",
  "SHE MAKES A CAKE",
  "HE DRIVES A TRUCK",
  "THE FLOWER IS BEAUTIFUL",
  "I DRINK WATER",
  "THE CAT PURRS",
  "SHE PAINTS A PICTURE",
  "HE PLAYS THE DRUMS",
  "THE RAIN STOPS",
  "I WRITE A LETTER",
  "THE DOG RUNS",
  "SHE READS A BOOK",
  "HE PLAYS THE VIOLIN",
  "THE TREE IS TALL",
  "I EAT LUNCH",
  "THE ROAD IS WIDE",
  "SHE SINGS A SONG",
  "HE PLAYS THE FLUTE",
  "THE RIVER IS DEEP",
  "I DRAW A PICTURE",
  "THE SKY IS BLUE",
  "SHE DRINKS COFFEE",
  "HE PLAYS THE GUITAR",
  "THE LEAVES ARE GREEN",
  "I GO TO WORK",
  "THE MOUNTAIN IS STEEP",
  "SHE RIDES A BIKE",
  "HE CATCHES A BALL",
  "THE SEA IS BLUE",
  "I WRITE A POEM",
  "THE SUN IS HOT",
  "SHE PLAYS THE VIOLIN",
  "HE TAKES A PHOTO",
  "THE BIRD IS SMALL",
  "I READ A BOOK",
  "THE WIND IS COLD",
  "SHE MAKES A SANDWICH",
  "HE DRIVES A BUS",
  "THE FLOWER IS RED",
  "I DRINK JUICE",
  "THE CAT IS SLEEPY",
  "SHE PAINTS A WALL",
  "HE PLAYS THE PIANO",
  "THE RAIN IS HEAVY",
  "I WRITE A REPORT",
  "THE DOG IS HAPPY",
  "SHE READS A NOVEL",
  "HE PLAYS THE TRUMPET",
  "THE TREE IS GREEN",
  "I EAT DINNER",
  "THE ROAD IS NARROW",
  "SHE SINGS A MELODY",
  "HE PLAYS THE SAXOPHONE",
  "THE RIVER IS WIDE",
  "I DRAW A SKETCH",
  "THE SKY IS GRAY",
  "SHE DRINKS MILK",
  "HE PLAYS THE CELLO",
  "THE LEAVES ARE FALLING",
  "I GO TO THE GYM",
  "THE MOUNTAIN IS SNOWY",
  "SHE RIDES A SCOOTER",
  "HE CATCHES A FISH",
  "THE SEA IS ROUGH",
  "I WRITE A BLOG",
  "THE SUN IS SHINING",
  "SHE PLAYS THE HARP",
  "HE TAKES A WALK",
  "THE BIRD IS SINGING",
  "I READ A NEWSPAPER",
  "THE WIND IS BREEZY",
  "SHE MAKES A PIE",
  "HE DRIVES A MOTORCYCLE",
  "THE FLOWER IS YELLOW",
  "I DRINK TEA",
  "THE CAT IS CURIOUS",
  "SHE PAINTS A LANDSCAPE",
  "HE PLAYS THE CLARINET",
  "THE RAIN IS LIGHT",
  "I WRITE A LETTER",
  "THE DOG IS FRIENDLY",
  "SHE READS A POEM",
  "HE PLAYS THE TROMBONE",
  "THE TREE IS BLOOMING",
  "I EAT A SNACK",
  "THE ROAD IS SMOOTH",
  "SHE SINGS A TUNE",
  "HE PLAYS THE OBOE",
  "THE RIVER IS CALM",
  "I DRAW A DIAGRAM",
  "THE SKY IS CLOUDY",
  "SHE DRINKS SODA",
  "HE PLAYS THE BASS",
  "THE LEAVES ARE DRY",
  "I GO TO THE STORE",
  "THE MOUNTAIN IS ROCKY",
  "SHE RIDES A SKATEBOARD",
  "HE CATCHES A BUTTERFLY",
  "THE SEA IS CLEAR",
  "I WRITE A JOURNAL",
  "THE SUN IS BRIGHT",
  "SHE PLAYS THE ACCORDION",
  "HE TAKES A NAP",
  "THE BIRD IS FLYING",
  "I READ A NOVEL",
  "THE WIND IS GUSTY",
  "SHE MAKES A SALAD",
  "HE DRIVES A VAN",
  "THE FLOWER IS PINK",
  "I DRINK COFFEE",
  "THE CAT IS PLAYFUL",
  "SHE PAINTS A PORTRAIT",
  "HE PLAYS THE HARMONICA",
  "THE RAIN IS POURING",
  "I WRITE A STORY",
  "THE DOG IS LOYAL",
  "SHE READS A MAGAZINE",
  "HE PLAYS THE BANJO",
  "THE TREE IS OLD",
  "I EAT A MEAL",
  "THE ROAD IS BUMPY",
  "SHE SINGS A BALLAD",
  "HE PLAYS THE MANDOLIN",
  "THE RIVER IS FLOWING",
  "I DRAW A MAP",
  "THE SKY IS BRIGHT",
  "SHE DRINKS WATER",
  "HE PLAYS THE TUBA",
  "THE LEAVES ARE WET",
  "I GO TO THE PARK",
  "THE MOUNTAIN IS MAJESTIC",
  "SHE RIDES A BIKE",
  "HE CATCHES A COLD",
  "THE SEA IS WARM",
  "I WRITE A LETTER",
  "THE SUN IS SETTING",
  "SHE PLAYS THE VIOLA",
  "HE TAKES A PICTURE",
  "THE BIRD IS CHIRPING",
  "I READ A BLOG",
  "THE WIND IS STRONG",
  "SHE MAKES A SMOOTHIE",
  "HE DRIVES A CAR",
  "THE FLOWER IS ORANGE",
  "I DRINK LEMONADE",
  "THE CAT IS HUNGRY",
  "SHE PAINTS A MURAL",
  "HE PLAYS THE TRUMPET",
  "THE RAIN IS DRIZZLING",
  "I WRITE A POEM",
  "THE DOG IS EXCITED",
  "SHE READS A STORY",
  "HE PLAYS THE XYLOPHONE",
  "THE TREE IS YOUNG",
  "I EAT A SANDWICH",
  "THE ROAD IS WINDING",
  "SHE SINGS A SONG",
  "HE PLAYS THE BONGO",
  "THE RIVER IS MUDDY",
  "I DRAW A HOUSE",
  "THE SKY IS DARK",
  "SHE DRINKS JUICE",
  "HE PLAYS THE SYNTHESIZER",
  "THE LEAVES ARE FALLING",
  "I GO TO THE BEACH",
  "THE MOUNTAIN IS TALL",
  "SHE RIDES A HORSE",
  "HE CATCHES A BALL",
  "THE SEA IS DEEP",
  "I WRITE A DIARY",
  "THE SUN IS RISING",
  "SHE PLAYS THE FLUTE",
  "HE TAKES A BREAK",
  "THE BIRD IS SINGING",
  "I READ A BOOK",
  "THE WIND IS BLOWING",
  "SHE MAKES A CAKE",
  "HE DRIVES A TRUCK",
  "THE FLOWER IS BLOOMING",
  "I DRINK WATER",
  "THE CAT IS PURRING",
  "SHE PAINTS A PICTURE",
  "HE PLAYS THE GUITAR",
  "THE RAIN IS FALLING",
  "I WRITE A LETTER",
  "THE DOG IS BARKING",
  "SHE READS A NOVEL",
  "HE PLAYS THE PIANO",
  "THE TREE IS GROWING",
  "I EAT BREAKFAST",
  "THE ROAD IS LONG",
  "SHE SINGS A SONG",
  "HE PLAYS THE DRUMS",
  "THE RIVER IS FLOWING",
  "I DRAW A PICTURE",
  "THE SKY IS BLUE",
  "SHE DRINKS COFFEE",
  "HE PLAYS THE VIOLIN",
  "THE LEAVES ARE GREEN",
  "I GO TO SCHOOL",
  "THE MOUNTAIN IS HIGH",
  "SHE RIDES A BIKE",
  "HE CATCHES A FISH",
  "THE SEA IS CALM",
  "I WRITE A STORY",
  "THE SUN IS SHINING",
  "SHE PLAYS THE PIANO",
  "HE TAKES A PHOTO",
  "THE BIRD IS FLYING",
  "I READ A MAGAZINE",
  "THE WIND IS STRONG",
  "SHE MAKES A SANDWICH",
  "HE DRIVES A BUS",
  "THE FLOWER IS BEAUTIFUL",
  "I DRINK JUICE",
  "THE CAT IS SLEEPING",
  "SHE PAINTS A WALL",
  "HE PLAYS THE PIANO",
  "THE RAIN IS HEAVY",
  "I WRITE A REPORT",
  "THE DOG IS HAPPY",
  "SHE READS A NOVEL",
  "HE PLAYS THE TRUMPET",
  "THE TREE IS GREEN",
  "I EAT DINNER",
  "THE ROAD IS NARROW",
  "SHE SINGS A MELODY",
  "HE PLAYS THE SAXOPHONE",
  "THE RIVER IS WIDE",
  "I DRAW A SKETCH",
  "THE SKY IS GRAY",
  "SHE DRINKS MILK",
  "HE PLAYS THE CELLO",
  "THE LEAVES ARE FALLING",
  "I GO TO THE GYM",
  "THE MOUNTAIN IS SNOWY",
  "SHE RIDES A SCOOTER",
  "HE CATCHES A BUTTERFLY",
  "THE SEA IS CLEAR",
  "I WRITE A BLOG",
  "THE SUN IS BRIGHT",
  "SHE PLAYS THE ACCORDION",
  "HE TAKES A WALK",
  "THE BIRD IS CHIRPING",
  "I READ A NEWSPAPER",
  "THE WIND IS BREEZY",
  "SHE MAKES A PIE",
  "HE DRIVES A MOTORCYCLE",
  "THE FLOWER IS YELLOW",
  "I DRINK TEA",
  "THE CAT IS CURIOUS",
  "SHE PAINTS A LANDSCAPE",
  "HE PLAYS THE CLARINET",
  "THE RAIN IS LIGHT",
  "I WRITE A LETTER",
  "THE DOG IS FRIENDLY",
  "SHE READS A POEM",
]