import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import localFont from "next/font/local";
import Navbar from "@/components/navbar";
import LenisProvider from "@/components/LenisProvider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

const myFont = localFont({
  src: './font/EurostileExtendedBlack.woff',
  variable: '--font-hero'
})

const general = localFont({
  src: './font/General.woff',
  variable: '--font-general'
})

const zentry = localFont({
  src: './font/zentry-regular.woff2',
  variable: '--font-zentry'
})

const popin = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-popin',
})

export const metadata: Metadata = {
  title: "Gamecrux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${popin.variable} ${zentry.variable} ${general.variable} ${myFont.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning={true}>
        <SessionProvider>
          <LenisProvider>
            <main className="flex flex-col min-h-screen bg-black">
              <Navbar />
              <div className="mt-[80px]">
                {children}
              </div>
            </main>
          </LenisProvider>
        </SessionProvider>
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
      </body>
    </html>
  );
}